FROM nginx:1.27-alpine

COPY nginx.cloud.conf /etc/nginx/nginx.cloud.conf
COPY routes.cloud.conf /etc/nginx/routes.conf
COPY docker-entrypoint.cloud.sh /docker-entrypoint.sh

RUN sed -i 's/\r$//' /docker-entrypoint.sh \
	&& chmod +x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]

EXPOSE 80
